### PR TITLE
checkpatch: add checkpatch image for eBPF code validation

### PR DESCRIPTION
**Pull request by qmonnet**
For its C code used to compile the eBPF datapath, Cilium follows the Linux kernel coding style, and uses the checkpatch.pl script to enforce it. This script has been copied into Cilium's repository, but it is hardly a good place. This introduce a large file in a language (perl) otherwise unused in the repository, and with a different license (GPL v2) than the rest of the code base.

Instead, we could have this script in image-tools to package it as a Docker image, which would be easy to pull for running checkpatch.pl. This PR introduces this new image.

The PR is split into several commit:

* The script checkpatch.pl is added first, along with its related files (spelling file, license file). This is to easily dissociate what comes from the Linux kernel, in order to ease the review. The files are aligned on those copied in the current version of Cilium (unaltered since extracted from the Linux repository).

* Additional files are added in a second commit: the bash wrapper to configure and use checkpatch.pl with Cilium, some documentation, and the Dockerfile to package the image. The bash script is taken from Cilium's repository with few modifications.

* The last commit fixes the bash script in order to make shellcheck happy.

Next step would be to remove checkpatch from Cilium's repository and to fix the way it is called in Makefile and GitHub actions to pull and run the Docker container built from this repository instead.

Addresses most of https://github.com/cilium/cilium/issues/12467.

### CODE REVIEW

**Review by errordeveloper — APPROVED** [review]
LGTM! Thanks a log @qmonnet 👍

**Review by errordeveloper — CHANGES_REQUESTED** [review]
Just realised, two things that are missing from here are:

- update to `Makefile`
- invocation in `.github/workflows/images.yaml`

Both of those should be just like any other single-platform image, e.g. `compilers`.

Overall this looks good!

**Comment by qmonnet** [comment]
Ah, I completely missed those indeed. Ok will add it, thanks for the review!

**Comment by qmonnet** [comment]
Done.
I also changed the way checkpatch.pl is patched (`-p1` instead of `-p2`. It should be more intuitive, and no longer needs a note in the README.md).

<details><summary>Incremental diff</summary>

``` diff
diff --git a/.github/workflows/images.yaml b/.github/workflows/images.yaml
index eae995a0af87..d054ef7a3066 100644
--- a/.github/workflows/images.yaml
+++ b/.github/workflows/images.yaml
@@ -109,3 +109,13 @@ jobs:
         with:
           entrypoint: make
           args: ca-certificates-image PUSH=true
+      - uses: docker://docker.io/cilium/image-maker:3475ee935e094acc5999f23a14253c3055fdc32f
+        name: Run make checkpatch-image
+        env:
+          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
+          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
+          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
+          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
+        with:
+          entrypoint: make
+          args: checkpatch-image PUSH=true
diff --git a/Makefile b/Makefile
index 91a69f4334f2..436a01e129b8 100644
--- a/Makefile
+++ b/Makefile
@@ -57,3 +57,6 @@ ca-certificates-image: .buildx_builder
 
 startup-script-image: .buildx_builder
 	PUSH=$(PUSH) EXPORT=$(EXPORT) scripts/build-image.sh startup-script images/startup-script linux/amd64,linux/arm64 "$$(cat .buildx_builder)" $(REGISTRIES)
+
+checkpatch-image: .buildx_builder
+	PUSH=$(PUSH) EXPORT=$(EXPORT) TEST=true scripts/build-image.sh cilium-checkpatch images/checkpatch linux/amd64 "$$(cat .buildx_builder)" $(REGISTRIES)
diff --git a/images/checkpatch/Dockerfile b/images/checkpatch/Dockerfile
index 5b843e159462..f6323e16f257 100644
--- a/images/checkpatch/Dockerfile
+++ b/images/checkpatch/Dockerfile
@@ -10,6 +10,6 @@ LABEL maintainer="maintainer@cilium.io"
 COPY . /opt/checkpatch
 
 WORKDIR /opt/checkpatch
-RUN for i in fixes/*.diff; do patch -p2 < "$i"; done
+RUN for i in fixes/*.diff; do patch -p1 < "$i"; done
 
 RUN apk add --no-cache bash git jq perl
diff --git a/images/checkpatch/README.md b/images/checkpatch/README.md
index 81f948285559..4e7b31af66d3 100644
--- a/images/checkpatch/README.md
+++ b/images/checkpatch/README.md
@@ -45,7 +45,3 @@ When building the Docker image, several patches are applied to the script.
   file instead of the `MAINTAINERS` used by the Linux kernel. Replace a few
   occurrences in `checkpatch.pl`, where relevant, to check and point to the
   correct owner file when new source code files are added.
-
-Note for creating new patches: The patches were created again the kernel
-repository, where `checkpatch.pl` is under `scripts/`, and a directory name is
-trimmed from the file path when patching (with `-p2`).
diff --git a/images/checkpatch/fixes/ignore-C99-comments-for-SPDX-tags.diff b/images/checkpatch/fixes/ignore-C99-comments-for-SPDX-tags.diff
index b403548d7989..37fb502471c7 100644
--- a/images/checkpatch/fixes/ignore-C99-comments-for-SPDX-tags.diff
+++ b/images/checkpatch/fixes/ignore-C99-comments-for-SPDX-tags.diff
@@ -1,7 +1,7 @@
 diff --git a/scripts/checkpatch.pl b/scripts/checkpatch.pl
 index 3cacc122c528..67f350c580ea 100755
---- a/scripts/checkpatch.pl
-+++ b/scripts/checkpatch.pl
+--- a/checkpatch.pl
++++ b/checkpatch.pl
 @@ -3983,7 +3983,10 @@ sub process {
  		}
  
diff --git a/images/checkpatch/fixes/use-CODEOWNERS-instead-of-MAINTAINERS.diff b/images/checkpatch/fixes/use-CODEOWNERS-instead-of-MAINTAINERS.diff
index 7d8b2ba07a26..ad994d97a9c1 100644
--- a/images/checkpatch/fixes/use-CODEOWNERS-instead-of-MAINTAINERS.diff
+++ b/images/checkpatch/fixes/use-CODEOWNERS-instead-of-MAINTAINERS.diff
@@ -1,7 +1,7 @@
 diff --git a/contrib/checkpatch/checkpatch.pl b/contrib/checkpatch/checkpatch.pl
 index 3cacc122c528..6a3f91f6af5f 100755
---- a/scripts/checkpatch.pl
-+++ b/scripts/checkpatch.pl
+--- a/checkpatch.pl
++++ b/checkpatch.pl
 @@ -1116,7 +1116,7 @@ EOM
  		print << "EOM"
  
```
</details>

**Review by errordeveloper — APPROVED** [review]

**Pull request merged**
